/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClaimIndexRouteImport } from './routes/claim.index'
import { Route as ClaimSettlementRouteImport } from './routes/claim.settlement'
import { Route as ApiSupportChatRouteImport } from './routes/api/support-chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimIndexRoute = ClaimIndexRouteImport.update({
  id: '/claim/',
  path: '/claim/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimSettlementRoute = ClaimSettlementRouteImport.update({
  id: '/claim/settlement',
  path: '/claim/settlement',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSupportChatRoute = ApiSupportChatRouteImport.update({
  id: '/api/support-chat',
  path: '/api/support-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/support-chat': typeof ApiSupportChatRoute
  '/claim/settlement': typeof ClaimSettlementRoute
  '/claim/': typeof ClaimIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/support-chat': typeof ApiSupportChatRoute
  '/claim/settlement': typeof ClaimSettlementRoute
  '/claim': typeof ClaimIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/support-chat': typeof ApiSupportChatRoute
  '/claim/settlement': typeof ClaimSettlementRoute
  '/claim/': typeof ClaimIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/support-chat' | '/claim/settlement' | '/claim/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/support-chat' | '/claim/settlement' | '/claim'
  id: '__root__' | '/' | '/api/support-chat' | '/claim/settlement' | '/claim/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSupportChatRoute: typeof ApiSupportChatRoute
  ClaimSettlementRoute: typeof ClaimSettlementRoute
  ClaimIndexRoute: typeof ClaimIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/': {
      id: '/claim/'
      path: '/claim'
      fullPath: '/claim/'
      preLoaderRoute: typeof ClaimIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/settlement': {
      id: '/claim/settlement'
      path: '/claim/settlement'
      fullPath: '/claim/settlement'
      preLoaderRoute: typeof ClaimSettlementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/support-chat': {
      id: '/api/support-chat'
      path: '/api/support-chat'
      fullPath: '/api/support-chat'
      preLoaderRoute: typeof ApiSupportChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSupportChatRoute: ApiSupportChatRoute,
  ClaimSettlementRoute: ClaimSettlementRoute,
  ClaimIndexRoute: ClaimIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
